
SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS)

SET(CMAKE_C_COMPILER mpixlc)
SET(CMAKE_CXX_COMPILER mpixlcxx)
SET(CMAKE_C_FLAGS "-O2 -qarch=qp -qtune=qp -DZF_LOG_OPTIMIZE_SIZE -D_POSIX_C_SOURCE=200809L")

SET(BUILD_SHARED_LIBS 0)

message(STATUS "Using the IBM compiler (BG/Q): ${CMAKE_C_COMPILER}")
