
SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)
SET(CMAKE_SHARED_LIBRARY_LINK_CXX_FLAGS)

SET(CMAKE_C_COMPILER cc)
SET(CMAKE_CXX_COMPILER CC)
SET(CMAKE_C_FLAGS "-O3 -std=c99 -D_POSIX_C_SOURCE=200809L")

SET(BUILD_SHARED_LIBS 0)

message(STATUS "Using Cray compilers: ${CMAKE_C_COMPILER}")
